queue_rules:
  - name: default
    conditions: []
pull_request_rules:
  - name: live poc stale approval direct
    conditions:
      - "#approved-reviews-by>=1"
      - "label=mergify-go"
    actions:
      merge:
        method: merge
