queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: gated merge on approval + label
    conditions:
      - "#approved-reviews-by>=1"
      - "label=mergify-go"
    actions:
      merge:
        method: merge
