name: autoapprove
on:
  pull_request_target:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review "$PRNUM" --approve -R "$REPO" -b "auto-approved by automation"
        env:
          GH_TOKEN: ${{ github.token }}
          PRNUM: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}